### ISSUE TITLE
Failed to build project for debug: `Cannot find type 'JSONRPC' in scope`

### ISSUE THREAD

**Issue by Andoran90** [WalletConnect/WalletConnectSwiftV2#1390]
**Describe the bug**
When upgrading to 1.19.0 and higher failed to build project in debug, because of `Cannot find type 'JSONRPC' in scope`. 
``` swift
func getSessionRequest(id: JSONRPC.RPCID) -> (request: Request, context: VerifyContext?)? {
    fatalError("Unimplemented")
}
```
Remove `JSONRPC.` so the project can be build in debug

**SDK Version**
 - Client: Swift
 - Version 1.19.0 and higher

**To Reproduce**
1. Add  pod 'WalletConnectSwiftV2', :git => 'https://github.com/WalletConnect/WalletConnectSwiftV2', :tag => '1.19.0'
2. Click on Build button
3. See error `Cannot find type 'JSONRPC' in scope`

**Expected behavior**
Build successful

**Screenshots**
<img width="2005" alt="image" src="https://github.com/user-attachments/assets/ae72d863-2891-4e33-98b7-4222fa61a0c1">

**Comment by llbartekll** [comment]
hey, I would guess it's some xcode issue, have you been able to resolve?

**Comment by Andoran90** [comment]
there is preprocessor `#if Debug`, so this code compiling for Debug builds. To resolve this I need to navigate to this file and remove `JSONRPC.`, because this doesn't exist. Swift doesn't support namespaces and there are no entity `JSONRPC`, so this is definitely should be removed.

**Comment by Andoran90** [comment]
@llbartekll hello.
Is there any updates on this?
